<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIsZ3YjW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIsZ3YjW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIsZ3YjW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIsZ3YjW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIsZ3YjW\App_KernelDevDebugContainer([
    'container.build_hash' => 'IsZ3YjW',
    'container.build_id' => 'e5c9f9f7',
    'container.build_time' => 1647528260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIsZ3YjW');
